name: Build MariaDB images

on:
  pull_request:
  workflow_dispatch:

jobs:
  generate-jobs:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build images
        run: |
          set -e -u -x
          make -C mariadb
      - name: Get images
        run: docker images
