name: Build MariaDB images

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/mariadb

jobs:
  build-images:
    name: Build images
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
        version:
          - "10.5"
          - "11.6"
          - "11.7"
    steps:
      - uses: actions/checkout@v4
      - name: Build image ${{ matrix.version }}
        run: |
          git clone https://github.com/MariaDB/mariadb-docker.git
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: mariadb-docker/${{ matrix.version }}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.version }}-${{ github.ref_name }}
          labels: |
            version=${{ matrix.version }}
            ref=${{ github.ref_name }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: ${{ startsWith(github.ref, 'refs/tags/') }}
