name: Build Rock

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: canonical/oci-factory/.github/workflows/Build-Rock.yaml@main
    with:
      oci-archive-name: mariadb-rock
      rock-repo: nicolasbock/container-images
      rock-repo-commit: main
      rockfile-directory: mariadb
